name: 'Sumar'
description: 'Dado dos números imprimirá el resultado'
inputs:
  a:
    description: 'First value'
    required: true
  b:
    description: 'Second value'
    required: true
outputs:
  resultado:
    description: "Resultado"
    value: ${{ steps.suma.outputs.resultado }}
runs:
  using: "composite"
  steps:
    - run: echo "Operación ${{ inputs.a }} + ${{ inputs.b }}."
      shell: bash
    - id: suma
      run: echo "::set-output name=resultado::$(echo $[${{ inputs.a }} + ${{ inputs.b }}] )"
      shell: bash
