
name: Sumar valores

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - id: suma
        uses: ./.github/workflows/mnico/sumar
        name: Sumar
        with:
          a: 5
          b: 4
      - run: echo suma ${{ steps.suma.outputs.resultado }}
        shell: bash